# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-29 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
