# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suburbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('min_lat', models.FloatField(blank=True, null=True)),
                ('min_lng', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True)),
                ('max_lng', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
