# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160730_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
