# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160730_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attendence_rate',
            field=models.FloatField(),
        ),
    ]
